name: 'Playwright Setup on Runner'
description: 'Set up Playwright on the runner: checkout code, install Node.js, cache dependencies, and install browsers.'

inputs:
  caching-dependencies:
    description: 'Whether to cache npm dependencies'
    required: false
    default: 'true'
  caching-browsers:
    description: 'Whether to cache Playwright browsers'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js (LTS)
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache npm Dependencies
      if: ${{ inputs.caching-dependencies == 'true' }}
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: deps-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install npm Dependencies
      if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' || inputs.caching-dependencies != 'true' }}
      run: npm install
      shell: bash

    - name: Cache Playwright Browsers
      if: ${{ inputs.caching-browsers == 'true' }}
      id: cache-browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ runner.os }}

    - name: Install Playwright Browsers (Chromium)
      if: ${{ steps.cache-browsers.outputs.cache-hit != 'true' || inputs.caching-browsers != 'true' }}
      run: npx playwright install --with-deps chromium
      shell: bash
