name: Playwright Sanity Tests

on:
  workflow_dispatch:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/playwright-setup
      - run: npm run sanity
      - uses: ./.github/actions/playwright-report
        if: always()
        with:
          test-step-outcome: ${{ job.status }}
