name: Playwright Smoke Tests

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/playwright-setup
      - run: npm run smoke
      - uses: ./.github/actions/allure-report
        if: always()
        with:
          test-step-outcome: ${{ job.status }}
